### ISSUE TITLE
Please add BTRFS

### ISSUE THREAD

**Issue by Crazyachmed** [JSkier21/linux-max98090#2]
My root is a btrfs volume, can you please add it back into the kernel? Done.

Add modules for other Cb (see below)

**Comment by JSkier21** [comment]
Sure thing, working on getting it updated today or tomorrow, will add it to the config.

Side note, mainline v5 does not fix anything, unfortunately.

**Comment by duffydack** [comment]
Didn't think it would, I've not seen anything on the ML.  I've asked the guy from redhat who dealt with it if he knows if/when it's applied upstream.....

**Comment by JSkier21** [comment]
Ball probably got dropped again.

Compiling 4.12 now with btrfs, should have it pushed here tonight or tomorrow.

**Comment by JSkier21** [comment]
@Crazyachmed please try it out, let me know how it works.

**Comment by duffydack** [comment]
And there we go ........I knew it

"It looks like v2 of the patch has fallen through the cracks. I've
just resend it, so hopefully it will get picked up now."

**Comment by JSkier21** [comment]
Thanks Duffy, I'll keep banging away on this when I have time until it gets fixed.

Closing the btrfs issue since it has been added. Other than loading the module, I do not have a way to test that on a root partition with Cb, so please let me know if you have any issues with it.

**Comment by Crazyachmed** [comment]
BTRFS now works fine, but unfortunatly it does not fix the audio (no device in pulseaudio, I did try some cycles of removing and installing the UCM files) on my TF103. Also a ton of other modules are missing, wifi, touchscreen and pen do not work and the touchpad only works in absolute mode :(

I'll take a look at compiling the kernel myself - it might well be that the sound issues come from some of the missing modules.

Thanks for the help though, I hoped it was a quick fix. The tablet seems to run so much smoother under Linux.

**Comment by JSkier21** [comment]
Yeah, config is for Swanky. Do you know what modules you need for the touch screen? I don't think Duffy is using the repo, and I don't mind adding more to get it fully running for you.

Reagrding the sound, it worked for me this morning, but did notice an increase in log errors for it. I'll check the last build and rebuild tonight if I missed something.

**Comment by duffydack** [comment]
@Crazyachmed booted core/linux to verify what hardware you have and sound works?  this patched build is to add stability to it (baytrail chromebook), but sound "works" in core/linux.

**Comment by Crazyachmed** [comment]
Hmm, my last real try is about half a year old, so it was 4.17/4.18? I remember that I played around with the modified UCM files and the best I managed was to get a bazillion sliders and toggels in alsamixer.

I will try again without pulse and get a list of the missing modules. What is that touchpad is now absolute business, any libinput vs. synaptics shenanigans? But on seconds thought, those aren't kernel drivers, aren't they?

**Comment by duffydack** [comment]
we all get the endless array of alsa mixers, it's silly, I don;t understand why they exist.  touchpad is controlled in userpace with libinput, and the kernel driver is CONFIG_MOUSE_ELAN_I2C.  It's probably the same for touchscreen 'CONFIG_TOUCHSCREEN_ELAN'.  I wouldn't worry about pulseaudio, that's not the issue with  sound on these devices - if anything it's helping.  
You're best just using core/linux (4.20 right now) and if sound doesn't work then unmute Left Speaker Mixer Left Dac and Right Speaker Mixer Right Dac in alsamixer.

**Comment by JSkier21** [comment]
Trying a rebuild now w/ elan touchscreen module. Will be .13, push coming shortly. 

What wifi module do you need @Crazyachmed?

**Comment by duffydack** [comment]
Worth noting, this patched kernel might not have any effect on whatever model the TF103 is, as there are quirks added for specific models (swanky and clapper are 2 of em)... so it might be pointless.

**Comment by Crazyachmed** [comment]
I've tried again with the stock kernel and also removed pulseaudio. Using "aplay -L" I only see some HDMI related sound devices, nothing else. Installing the UCM files from AUR does not change anything (do I need to do anything besides reboot?).

Regarding your modified kernel, which I understand does not make much sense to use currently, has the following modules loaded, that I do not have in stock "iTCO_vendor_support, iTCO_wdt". On the other hand the following modules are not loaded (most of them will be dependancies and not actually missing, I guess) "8250_dw, ac97_bus, acpi_thermal_rel, arc4, ath, ath10k_core, ath10k_pci, ccm, cfg80211, cifs, dns_resolver, fscache, gpio_keys, hid_logitech_dj, hid_logitech_hidpp, hid_multitouch, hid_sensor_accel_3d, hid_sensor_hub, hid_sensor_iio_common, hid_sensor_trigger, i2c_hid, industrialio, industrialio_triggered_buffer, int3400_thermal, int3403_thermal, int3406_thermal, int340x_thermal_zone, intel_atomisp2_pm, intel_chtdc_ti_pwrbtn, intel_hid, intel_int0002_vgpio, intel_ish_ipc, intel_ishtp, intel_ishtp_hid, intel_soc_dts_iosf, intel_soc_pmic_chtdc_ti, intel_xhci_usb_role_switch, kfifo_buf, kvmgt, mac80211, mac_hid, md4, mdev, mei, mei_txe, msr, nls_utf8, processor_thermal_device, roles, serio, snd_hdmi_lpe_audio, snd_pcm_dmaengine, soc_button_array, sparse_keymap, spi_pxa2xx_platform, tpm_crb, vfio, vfio_iommu_type1, vfio_mdev, wdat_wdt, wmi"

Do you have any ideas how I can get the internal speakers to run?

**Comment by Crazyachmed** [comment]
It looks I also got the model slightly wrong, I have an T103HAF (I think the F only denotes the internal SSD size)

**Comment by duffydack** [comment]
Are you sure you have a baytrail device with max98090 audio?  I don't think you have tbh.

**Comment by Crazyachmed** [comment]
It's and Atom Atom x5-Z8350, so Cherrytrail, but regarding audio it was always mentioned as very similar to Baytrail. How can I find info about the sound chip? There was something about renaming in the UCM directory, but that never really worked.

**Comment by duffydack** [comment]
According to interwebs, your devices sound is HDMI and LPE which pipes over HDMI (HdmiLpeAudio), so not supported whatsoever in this custom kernel.  Found reference to bytcht-nocodec driver, no idea if it works or not, but it's enabled in core/linux so grab the ucm for it from https://github.com/plbossart/UCM, see what happens.  If you still have issue, you'll get better support (they're great) in #alsa on freenode.

**Comment by JSkier21** [comment]
Yep, different sound chip set, not max980900, this won't work for you unfortunately. 

Leaving this open until I update the config, probably next build.  

Remove:
* BTRFS
* CONFIG_TOUCHSCREEN_ELAN

**Comment by JSkier21** [comment]
Removed:

- BTRFS
- CONFIG_TOUCHSCREEN_ELAN

**Comment by Crazyachmed** [comment]
Thanks for the help anyhow!

**Comment by JSkier21** [comment]
> Thanks for the help anyhow!

No problem, hopefully you can figure something out with your chip set. Wish these were a bit easier to get working fully.
